services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        DEVCONTAINER_INSTALL_ONLY: "1"
    command: sleep infinity
    environment:
      - RAILS_ENV=development
      - BUNDLE_DEPLOYMENT=0
      - BUNDLE_WITHOUT=
      - BUNDLE_PATH=/rails/vendor/bundle
      - BUNDLE_APP_CONFIG=/rails/.bundle
      - BUNDLE_DISABLE_SHARED_GEMS=true
    env_file: !reset []
